# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Disabled Python application workflow

on: []

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - name: Disabled workflow
        run: echo "This workflow is disabled. Use .github/workflows/ci.yml instead."
